# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacey < Formula
  desc "Twitter spaces search CLI"
  homepage "https://github.com/rothgar/spacey-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rothgar/spacey-cli/releases/download/0.1.2/spacey_0.1.2_Darwin_arm64.tar.gz"
      sha256 "ad66fe79fe1c7ec9a19e6f83ed5a9864bc74905366c2ffce20ad843a906a8417"

      def install
        bin.install "spacey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rothgar/spacey-cli/releases/download/0.1.2/spacey_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "f669eae70e35f0ec0e9389217846ede683172a95532966ba6b27321969ae5b54"

      def install
        bin.install "spacey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rothgar/spacey-cli/releases/download/0.1.2/spacey_0.1.2_Linux_x86_64.tar.gz"
      sha256 "25cab53acb62ce95dcfb5402f264b0f74525fd8a130d65f5d0ef9fe68cf30904"

      def install
        bin.install "spacey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rothgar/spacey-cli/releases/download/0.1.2/spacey_0.1.2_Linux_arm64.tar.gz"
      sha256 "f6255a2e8d86984f7e8da11a0b706a7cc3511fe726186069bd8b585d35caa409"

      def install
        bin.install "spacey"
      end
    end
  end
end
