# This file was generated by GoReleaser. DO NOT EDIT.
cask "k" do
  version "0.6.0"

  on_macos do
    sha256 "56dc76880e8b3b5313e59a4c2ee7d5aed956c801c7c3d5453521540258319704"
    url "https://github.com/rothgar/k/releases/download/v#{version}/k_#{version}_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "d7faab97b910a06b66d3f8557e93c79107e979980c519a95c454ce54921e758d"
      url "https://github.com/rothgar/k/releases/download/v#{version}/k_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "64084a5b5b7ec5f99b9003c0434e6d050019eef290e137ce97239ab0e7fee173"
      url "https://github.com/rothgar/k/releases/download/v#{version}/k_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "k"
  desc "Experimental kubectl wrapper for advanced multi-cluster management"
  homepage "https://github.com/rothgar/k"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k"

  # No zap stanza required

end
