# This file was generated by GoReleaser. DO NOT EDIT.
class Awsls < Formula
  desc "A list command for AWS resources"
  homepage "https://github.com/jckuester/awsls"
  version "1.16.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rothgar/awsls/releases/download/v1.16.0/awsls_1.16.0_darwin_amd64.tar.gz"
    sha256 "aac2e430f7521488212d07e9e3aa0d2190b367dda17684039d3336aeb7338057"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rothgar/awsls/releases/download/v1.16.0/awsls_1.16.0_linux_amd64.tar.gz"
      sha256 "f58a743e71696372a398d168f0cc48ddc0bb9f7ced09a765c50fcf23f8632ff1"
    end
  end

  def install
    bin.install "awsls"
  end
end
