# This file was generated by GoReleaser. DO NOT EDIT.
class K < Formula
  desc "Experimental kubectl wrapper"
  homepage "https://github.com/rothgar/k"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rothgar/k/releases/download/0.3.1/k_0.3.1_Darwin_x86_64.tar.gz"
    sha256 "83764e531d65df71ada70893a25bb41f31b826be4cae96afb0b0cc2aeaaff78f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rothgar/k/releases/download/0.3.1/k_0.3.1_Linux_x86_64.tar.gz"
      sha256 "1871be418a801e18974d3d630b55329553c6ca15649a280a3b19a6c00e0d71a4"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rothgar/k/releases/download/0.3.1/k_0.3.1_Linux_arm64.tar.gz"
        sha256 "b7c9dd28b86bc5da57c1c86432b40563cbfd059bfa4d8e07ff8fca2ecd0665a5"
      else
      end
    end
  end
  
  depends_on "kubectl"

  def install
    bin.install "bin/k"
    bash_completion.install "completions/bash/k"
  end

  test do
    system "#{bin}/k"
  end
end
