# This file was generated by GoReleaser. DO NOT EDIT.
class K < Formula
  desc "Experimental kubectl wrapper"
  homepage "https://github.com/rothgar/k"
  version "0.3.4"

  if OS.mac?
    url "https://github.com/rothgar/k/releases/download/0.3.4/k_0.3.4_Darwin_x86_64.tar.gz"
    sha256 "2f828d1dd57061b5d198fb7626f96e116c0befd7d6c4adfaf8ba62f462970a8c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rothgar/k/releases/download/0.3.4/k_0.3.4_Linux_x86_64.tar.gz"
      sha256 "c60dbe5de3569038fe8d078bf7f82b7f1f44d2624b60b1496b50600a858f2238"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rothgar/k/releases/download/0.3.4/k_0.3.4_Linux_arm64.tar.gz"
        sha256 "1ac3c7e5932f3c1a08fe35c17ba531c4eadc289ce456c7a6495b7e04bab1e7c3"
      else
      end
    end
  end

  depends_on "kubectl"

  def install
    bin.install "bin/k"
    bash_completion.install "completions/bash/k"
  end

  test do
    system "#{bin}/k"
  end
end
