# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K < Formula
  desc "Experimental kubectl wrapper for advanced multi-cluster management"
  homepage "https://github.com/rothgar/k"
  version "0.5.0"
  license "Apache-2.0"

  depends_on "kubectl" => :required

  on_macos do
    url "https://github.com/rothgar/k/releases/download/v0.5.0/k_0.5.0_Darwin_all.tar.gz"
    sha256 "0567abdfae3a67d1c8013e011d7faec78c41c466e68d0b1fef93433849f7fa80"

    define_method(:install) do
      bin.install "k"
      bash_completion.install "completions/k" => "k"
      zsh_completion.install "completions/_k" => "_k"
      fish_completion.install "completions/k.fish" => "k.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rothgar/k/releases/download/v0.5.0/k_0.5.0_Linux_x86_64.tar.gz"
      sha256 "dc8676d6373e067ae552b2d26be309fda7707efef32253ad2400aa3eaa7628e3"
      define_method(:install) do
        bin.install "k"
        bash_completion.install "completions/k" => "k"
        zsh_completion.install "completions/_k" => "_k"
        fish_completion.install "completions/k.fish" => "k.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rothgar/k/releases/download/v0.5.0/k_0.5.0_Linux_armv6.tar.gz"
      sha256 "cf4a112d5e99d6a2095d71ba1095ac3548b24508ed40b7e70c03af50e13338d0"
      define_method(:install) do
        bin.install "k"
        bash_completion.install "completions/k" => "k"
        zsh_completion.install "completions/_k" => "_k"
        fish_completion.install "completions/k.fish" => "k.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rothgar/k/releases/download/v0.5.0/k_0.5.0_Linux_arm64.tar.gz"
      sha256 "e8ff4964e2b0ba21dae91facea60aad006ec1a1b5d175ca4a35847e51691dabd"
      define_method(:install) do
        bin.install "k"
        bash_completion.install "completions/k" => "k"
        zsh_completion.install "completions/_k" => "_k"
        fish_completion.install "completions/k.fish" => "k.fish"
      end
    end
  end

  test do
    system "#{bin}/k", "--help"
  end
end
