# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecolor < Formula
  desc "Colorize your kubectl output"
  homepage "https://github.com/rothgar/kubecolor"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rothgar/kubecolor/releases/download/v0.0.7/kubecolor_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "b88f7792d6c3843788b03a3d8ee661953511404237635320ac78e0a886d45d43"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rothgar/kubecolor/releases/download/v0.0.7/kubecolor_0.0.7_Linux_x86_64.tar.gz"
      sha256 "d4893a27a28a3ac3510cbb7654aeebe2025438706fe6b9c65d2cf39e891c0163"
    end
  end

  def install
    bin.install "kubecolor"
  end
end
